def get_parameters(substance):
    '''
    Returns the set of parameter given a substance. 
    Possible substances are silica ("SiO2" or "silica"), water ("H2O" or "water")
    or a combination ("SiO2H2O" or "H2OSiO2" or "silicawater" or "watersilica").
    '''
    if substance == "silica" or substance == "sio2":
        '''
        Default parameters taken from Vashishta 1990.
        '''
        SiSiSi = {"H" : 0.82023, 
                  "eta" : 11, 
                  "Zi" : 1.6, 
                  "Zj" : 1.6, 
                  "lambda1" : 999, 
                  "D" : 0.0, 
                  "lambda4" : 4.43, 
                  "W" : 0.0, 
                  "rc" : 10.0, 
                  "B" : 0.0, 
                  "gamma" : 0.0, 
                  "r0" : 0.0, 
                  "C" : 0.0, 
                  "cos(theta)" : 0.0}
    
        OOO = {"H" : 7.43848, 
               "eta" : 7, 
               "Zi" : -0.8, 
               "Zj" : -0.8, 
               "lambda1" : 999, 
               "D" : 22.1179, 
               "lambda4" : 4.43, 
               "W" : 0.0, 
               "rc" : 10.0, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0" : 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 0.0}
    
        OSiSi = {"H" : 163.859, 
                 "eta" : 9, 
                 "Zi" : -0.8, 
                 "Zj" : 1.6, 
                 "lambda1" : 999, 
                 "D" : 44.2357, 
                 "lambda4" : 4.43, 
                 "W" : 0.0, 
                 "rc" : 10.0, 
                 "B" : 20.146, 
                 "gamma" : 1.0, 
                 "r0": 2.60, 
                 "C" : 0.0, 
                 "cos(theta)" : -0.77714596}
    
        SiOO = {"H" : 163.859, 
                "eta" : 9, 
                "Zi" : 1.6, 
                "Zj" : -0.8, 
                "lambda1" : 999, 
                "D" : 44.2357, 
                "lambda4" : 4.43, 
                "W" : 0.0, 
                "rc" : 10.0, 
                "B" : 5.0365, 
                "gamma" : 1.0, 
                "r0": 2.60, 
                "C" : 0.0, 
                "cos(theta)" : -0.33333333333333333}
    
        SiOSi = {"H" : 0.0, 
                 "eta" : 0.0, 
                 "Zi" : 0.0, 
                 "Zj" : 0.0, 
                 "lambda1" : 0.0, 
                 "D" : 0.0, 
                 "lambda4" : 0.0, 
                 "W" : 0.0, 
                 "rc" : 0.0, 
                 "B" : 0.0, 
                 "gamma" : 0.0, 
                 "r0": 0.0, 
                 "C" : 0.0, 
                 "cos(theta)" : 0.0}
    
        SiSiO = {"H" : 0.0, 
                 "eta" : 0.0, 
                 "Zi" : 0.0, 
                 "Zj" : 0.0, 
                 "lambda1" : 0.0, 
                 "D" : 0.0, 
                 "lambda4" : 0.0, 
                 "W" : 0.0, 
                 "rc" : 0.0, 
                 "B" : 0.0, 
                 "gamma" : 0.0, 
                 "r0": 0.0, 
                 "C" : 0.0, 
                 "cos(theta)" : 0.0}
    
        OSiO = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0, 
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 0.0}
    
        OOSi = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0, 
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 0.0}
    
        parameters = {"SiSiSi" : SiSiSi, 
                      "OOO" : OOO, 
                      "OSiSi" : OSiSi, 
                      "SiOO" : SiOO, 
                      "SiOSi" : SiOSi, 
                      "SiSiO" : SiSiO, 
                      "OSiO" : OSiO, 
                      "OOSi" : OOSi}
        masses = {"Si" : 28.08, "O" : 15.9994}
        return parameters, masses
        
    elif substance == "water" or substance == "h2o":
        '''
        Default parameters taken from Wang et al.
        '''
        HHH = {"H" : 0.0, 
               "eta" : 9, 
               "Zi" : 0.32983, 
               "Zj" : 0.32983, 
               "lambda1" : 4.43, 
               "D" : 0.0, 
               "lambda4" : 2.5, 
               "W" : 0.0, 
               "rc" : 5.5, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0" : 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        OOO = {"H" : 1965.88, 
               "eta" : 9, 
               "Zi" : -0.65966, 
               "Zj" : -0.65966, 
               "lambda1" : 4.43, 
               "D" : 2.0887, 
               "lambda4" : 2.5, 
               "W" : 10.0, 
               "rc" : 5.5, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0" : 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        OHH = {"H" : 0.61437, 
               "eta" : 9, 
               "Zi" : -0.65966, 
               "Zj" : 0.32983, 
               "lambda1" : 4.43,   
               "D" : 0.2611, 
               "lambda4" : 1.51113, 
               "W" : 0.0, 
               "rc" : 5.5, 
               "B" : 52.9333, 
               "gamma" : 0.75, 
               "r0": 1.4, 
               "C" : 0.0, 
               "cos(theta)" : -0.138267391}
    
        HOO = {"H" : 0.61437, 
               "eta" : 9, 
               "Zi" : 0.32983, 
               "Zj" : -0.65966, 
               "lambda1" : 4.43,   
               "D" : 0.2611, 
               "lambda4" : 1.51113, 
               "W" : 0.0, 
               "rc" : 5.5, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        HOH = {"H" : 0.0, 
               "eta" : 0.0, 
               "Zi" : 0.0, 
               "Zj" : 0.0, 
               "lambda1" : 0.0,   
               "D" : 0.0, 
               "lambda4" : 0.0, 
               "W" : 0.0, 
               "rc" : 0.0, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        HHO = {"H" : 0.0, 
               "eta" : 0.0, 
               "Zi" : 0.0, 
               "Zj" : 0.0, 
               "lambda1" : 0.0,   
               "D" : 0.0, 
               "lambda4" : 0.0, 
               "W" : 0.0, 
               "rc" : 0.0, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        OHO = {"H" : 0.0, 
               "eta" : 0.0, 
               "Zi" : 0.0, 
               "Zj" : 0.0, 
               "lambda1" : 0.0,   
               "D" : 0.0, 
               "lambda4" : 0.0, 
               "W" : 0.0, 
               "rc" : 0.0, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        OOH = {"H" : 0.0, 
               "eta" : 0.0, 
               "Zi" : 0.0, 
               "Zj" : 0.0, 
               "lambda1" : 0.0,   
               "D" : 0.0, 
               "lambda4" : 0.0, 
               "W" : 0.0, 
               "rc" : 0.0, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        parameters = {"HHH" : HHH, 
                      "OOO" : OOO, 
                      "OHH" : OHH, 
                      "HOO" : HOO, 
                      "HOH" : HOH, 
                      "HHO" : HHO, 
                      "OHO" : OHO, 
                      "OOH" : OOH}
        masses = {"H" : 1.008, "O" : 15.9994}
        return parameters, masses
        
    elif substance == "silicawater" or substance == "watersilica" or \
         substance == "h2osio2" or substance == "sio2h2o":
        '''
        Default parameters taken from Wang et al.
        '''
        SiSiSi = {"H" : 0.39246, 
                  "eta" : 11, 
                  "Zi" : 1.2, 
                  "Zj" : 1.2, 
                  "lambda1" : 4.43, 
                  "D" : 0.0, 
                  "lambda4" : 2.5, 
                  "W" : 0.0, 
                  "rc" : 5.5, 
                  "B" : 0.0, 
                  "gamma" : 0.0, 
                  "r0" : 0.0, 
                  "C" : 0.0, 
                  "cos(theta)" : 0.0}
    
        OOO = {"H" : 355.5263, 
               "eta" : 7, 
               "Zi" : -0.6, 
               "Zj" : -0.6, 
               "lambda1" : 4.43, 
               "D" : 12.4413912, 
               "lambda4" : 2.5, 
               "W" : 0.0, 
               "rc" : 5.5, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0" : 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 0.0}
    
        OSiSi = {"H" : 78.3143, 
                 "eta" : 9, 
                 "Zi" : -0.6, 
                 "Zj" : 1.2, 
                 "lambda1" : 4.43, 
                 "D" : 24.8827823, 
                 "lambda4" : 2.5, 
                 "W" : 0.0, 
                 "rc" : 5.5, 
                 "B" : 19.972, 
                 "gamma" : 1.0, 
                 "r0": 2.60, 
                 "C" : 0.0, 
                 "cos(theta)" : -0.77714596}
    
        SiOO = {"H" : 78.3143, 
                "eta" : 9, 
                "Zi" : 1.2, 
                "Zj" : -0.6, 
                "lambda1" : 4.43, 
                "D" : 24.8827823, 
                "lambda4" : 2.5, 
                "W" : 0.0, 
                "rc" : 5.5, 
                "B" : 4.993, 
                "gamma" : 1.0, 
                "r0": 2.60, 
                "C" : 0.0, 
                "cos(theta)" : -0.333313248}
    
        SiOSi = {"H" : 0.0, 
                 "eta" : 0.0, 
                 "Zi" : 0.0, 
                 "Zj" : 0.0, 
                 "lambda1" : 0.0, 
                 "D" : 0.0, 
                 "lambda4" : 0.0, 
                 "W" : 0.0, 
                 "rc" : 0.0, 
                 "B" : 0.0, 
                 "gamma" : 0.0, 
                 "r0": 0.0, 
                 "C" : 0.0, 
                 "cos(theta)" : 0.0}
    
        SiSiO = {"H" : 0.0, 
                 "eta" : 0.0, 
                 "Zi" : 0.0, 
                 "Zj" : 0.0, 
                 "lambda1" : 0.0, 
                 "D" : 0.0, 
                 "lambda4" : 0.0, 
                 "W" : 0.0, 
                 "rc" : 0.0, 
                 "B" : 0.0, 
                 "gamma" : 0.0, 
                 "r0": 0.0, 
                 "C" : 0.0, 
                 "cos(theta)" : 0.0}
    
        OSiO = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0, 
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 0.0}
    
        OOSi = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0, 
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 0.0}
        
        HHH = {"H" : 0.0, 
               "eta" : 9, 
               "Zi" : 0.32983, 
               "Zj" : 0.32983, 
               "lambda1" : 4.43, 
               "D" : 0.0, 
               "lambda4" : 2.5, 
               "W" : 0.0, 
               "rc" : 5.5, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0" : 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        OOO = {"H" : 1965.88, 
               "eta" : 9, 
               "Zi" : -0.65966, 
               "Zj" : -0.65966, 
               "lambda1" : 4.43, 
               "D" : 2.0887, 
               "lambda4" : 2.5, 
               "W" : 10.0, 
               "rc" : 5.5, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0" : 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        OHH = {"H" : 0.61437, 
               "eta" : 9, 
               "Zi" : -0.65966, 
               "Zj" : 0.32983, 
               "lambda1" : 4.43,   
               "D" : 0.2611, 
               "lambda4" : 1.51113, 
               "W" : 0.0, 
               "rc" : 5.5, 
               "B" : 52.9333, 
               "gamma" : 0.75, 
               "r0": 1.4, 
               "C" : 0.0, 
               "cos(theta)" : -0.138267391}
    
        HOO = {"H" : 0.61437, 
               "eta" : 9, 
               "Zi" : 0.32983, 
               "Zj" : -0.65966, 
               "lambda1" : 4.43,   
               "D" : 0.2611, 
               "lambda4" : 1.51113, 
               "W" : 0.0, 
               "rc" : 5.5, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        HOH = {"H" : 0.0, 
               "eta" : 0.0, 
               "Zi" : 0.0, 
               "Zj" : 0.0, 
               "lambda1" : 0.0,   
               "D" : 0.0, 
               "lambda4" : 0.0, 
               "W" : 0.0, 
               "rc" : 0.0, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        HHO = {"H" : 0.0, 
               "eta" : 0.0, 
               "Zi" : 0.0, 
               "Zj" : 0.0, 
               "lambda1" : 0.0,   
               "D" : 0.0, 
               "lambda4" : 0.0, 
               "W" : 0.0, 
               "rc" : 0.0, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        OHO = {"H" : 0.0, 
               "eta" : 0.0, 
               "Zi" : 0.0, 
               "Zj" : 0.0, 
               "lambda1" : 0.0,   
               "D" : 0.0, 
               "lambda4" : 0.0, 
               "W" : 0.0, 
               "rc" : 0.0, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
    
        OOH = {"H" : 0.0, 
               "eta" : 0.0, 
               "Zi" : 0.0, 
               "Zj" : 0.0, 
               "lambda1" : 0.0,   
               "D" : 0.0, 
               "lambda4" : 0.0, 
               "W" : 0.0, 
               "rc" : 0.0, 
               "B" : 0.0, 
               "gamma" : 0.0, 
               "r0": 0.0, 
               "C" : 0.0, 
               "cos(theta)" : 1.0}
               
        HSiSi = {"H" : 0.0, 
                 "eta" : 0.0, 
                 "Zi" : 0.0, 
                 "Zj" : 0.0, 
                 "lambda1" : 0.0,   
                 "D" : 0.0, 
                 "lambda4" : 0.0, 
                 "W" : 0.0, 
                 "rc" : 0.0, 
                 "B" : 0.0, 
                 "gamma" : 0.0, 
                 "r0": 0.0, 
                 "C" : 0.0, 
                 "cos(theta)" : 1.0}
                 
        SiHH = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0,   
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 1.0}
                
        SiSiH = {"H" : 0.0, 
                 "eta" : 0.0, 
                 "Zi" : 0.0, 
                 "Zj" : 0.0, 
                 "lambda1" : 0.0,   
                 "D" : 0.0, 
                 "lambda4" : 0.0, 
                 "W" : 0.0, 
                 "rc" : 0.0, 
                 "B" : 0.0, 
                 "gamma" : 0.0, 
                 "r0": 0.0, 
                 "C" : 0.0, 
                 "cos(theta)" : 1.0}
                 
        SiHSi = {"H" : 0.0, 
                 "eta" : 0.0, 
                 "Zi" : 0.0, 
                 "Zj" : 0.0, 
                 "lambda1" : 0.0,   
                 "D" : 0.0, 
                 "lambda4" : 0.0, 
                 "W" : 0.0, 
                 "rc" : 0.0, 
                 "B" : 0.0, 
                 "gamma" : 0.0, 
                 "r0": 0.0, 
                 "C" : 0.0, 
                 "cos(theta)" : 1.0}
                 
        HSiH = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0,   
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 1.0}
                
        HHSi = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0,   
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 1.0}
                
        OSiH = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0,   
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 1.0}
                
        OHSi = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0,   
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 1.0}
                
        SiOH = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0,   
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 1.0}
                
        SiHO = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0,   
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 1.0}
                
        HSiO = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0,   
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 1.0}
                
        HOSi = {"H" : 0.0, 
                "eta" : 0.0, 
                "Zi" : 0.0, 
                "Zj" : 0.0, 
                "lambda1" : 0.0,   
                "D" : 0.0, 
                "lambda4" : 0.0, 
                "W" : 0.0, 
                "rc" : 0.0, 
                "B" : 0.0, 
                "gamma" : 0.0, 
                "r0": 0.0, 
                "C" : 0.0, 
                "cos(theta)" : 1.0}
    
        parameters = {"SiSiSi" : SiSiSi, 
                      "OOO" : OOO, 
                      "OSiSi" : OSiSi, 
                      "SiOO" : SiOO, 
                      "SiOSi" : SiOSi, 
                      "SiSiO" : SiSiO, 
                      "OSiO" : OSiO, 
                      "OOSi" : OOSi,
                      "HHH" : HHH, 
                      "OOO" : OOO, 
                      "OHH" : OHH, 
                      "HOO" : HOO, 
                      "HOH" : HOH, 
                      "HHO" : HHO, 
                      "OHO" : OHO, 
                      "OOH" : OOH,
                      "HSiSi" : HSiSi,
                      "SiHH" : SiHH,
                      "SiHSi" : SiHSi,
                      "HSiH" : HSiH,
                      "HHSi" : HHSi,
                      "OSiH" : OSiH,
                      "OHSi" : OHSi,
                      "SiOH" : SiOH,
                      "SiHO" : SiHO,
                      "HSiO" : HSiO,
                      "HOSi" : HOSi}
        masses = {"Si" : 28.08, "H" : 1.008, "O" : 15.9994}
        return parameters, masses
        
    else:
        raise NameError("The substance {} has no default parameters.".format(substance))
